Repository larryyueli/velocity, pull requests merged in 2018-04, with the labels that each got.

#69 Issue 62
  API/api-components/projects-api.js
  API/api-components/teams-api.js
  API/api-components/tickets-api.js
  Locales/en.json
  Templates/projects/project-page.pug
  Templates/projects/project-team.pug
  Templates/projects/projects-add-content.pug
  Templates/projects/projects-group-user-entry.pug
  Templates/projects/team-board.pug
  Templates/projects/team-entry.pug
  Templates/projects/team-management.pug
  Templates/tickets/board-entry.pug
  Templates/tickets/sprint-entry.pug
  Templates/tickets/ticket-entry.pug
  Templates/tickets/tickets-edit.pug
  UI/js/common.js
  UI/js/projects/project-page.js
  UI/js/projects/project-team.js
  UI/js/projects/projects-add-content.js
  UI/js/projects/projects.js
  UI/js/projects/sprint-active.js
  UI/js/projects/team-backlog.js
  UI/js/projects/team-board.js
  UI/js/projects/team-issues.js
  UI/js/users/users.js
  sass/css/common.scss
  sass/css/project-team.scss
  sass/css/sprint-active.scss
Labels: Feature, bug, enhancement

#70 Issue 68
  API/api-components/common-api.js
  API/api-components/projects-api.js
  API/api-components/releases-api.js
  API/api-components/sprints-api.js
  API/api-components/tags-api.js
  API/api-components/teams-api.js
  API/api-components/tickets-api.js
  API/api-components/users-api.js
  API/api-handler.js
  Backend/common.js
  Backend/customFileSystem.js
  Backend/project-components/project-tickets.js
  Backend/projects.js
  Locales/en.json
  Templates/projects/project-page.pug
  Templates/projects/projects-add-content.pug
  Templates/projects/projects-add.pug
  Templates/projects/release-page.pug
  Templates/projects/sprint-page.pug
  Templates/projects/tag-page.pug
  Templates/projects/team-management-release-entry.pug
  Templates/projects/team-management-sprint-entry.pug
  Templates/projects/team-management-tag-entry.pug
  Templates/projects/team-management.pug
  Templates/projects/team-overview.pug
  Templates/tickets/tickets-edit.pug
  Templates/tickets/tickets-entry.pug
  UI/js/common.js
  UI/js/projects/project-page.js
  UI/js/projects/project-team.js
  UI/js/projects/projects-add-content.js
  UI/js/projects/projects-add.js
  UI/js/projects/release-page.js
  UI/js/projects/sprint-page.js
  UI/js/projects/tag-page.js
  UI/js/tickets/tickets-edit.js
  UI/js/tickets/tickets-entry.js
  UI/js/users/users.js
  sass/css/common.scss
  sass/css/themes/themes.scss
  velocity.js
Labels: Feature, bug, enhancement

#72 Analytics.....
  API/api-components/analytics-api.js
  API/api-components/projects-api.js
  API/api-components/releases-api.js
  API/api-components/sprints-api.js
  API/api-components/teams-api.js
  API/api-handler.js
  Backend/analytics-components/analytics-admin.js
  Backend/analytics-components/analytics-kanban.js
  Backend/analytics-components/analytics-releases.js
  Backend/analytics-components/analytics-sprints.js
  Backend/analytics.js
  Backend/db.js
  Backend/dbs/db-analytics-admin.js
  Backend/dbs/db-analytics-kanban.js
  Backend/dbs/db-analytics-releases.js
  Backend/dbs/db-analytics-sprints.js
  Backend/project-components/project-releases.js
  Backend/project-components/project-sprints.js
  Backend/project-components/project-teams.js
  Backend/project-components/project-tickets.js
  Backend/projects.js
  Locales/en.json
  Templates/layout.pug
  Templates/projects/project-page.pug
  Templates/projects/project-team.pug
  Templates/projects/team-analytics.pug
  UI/js/common.js
  UI/js/projects/project-page.js
  UI/js/projects/project-team.js
  UI/js/projects/team-analytics.js
  package.json
  sass/css/common.scss
  sass/css/team-analytics.scss
  sass/css/themes/themes.scss
  velocity.js
Labels: Feature, bug

#76 view mode of tickets before edit
  API/api-components/tickets-api.js
  Templates/tickets/tickets-edit.pug
  UI/js/tickets/tickets-edit.js
  sass/css/common.scss
Labels: Feature

#79 Bug fixes
  Templates/projects/project-page.pug
  Templates/projects/project-team.pug
  Templates/tickets/tickets-edit.pug
  UI/js/common.js
  UI/js/projects/project-page.js
  UI/js/projects/project-team.js
  UI/js/projects/team-analytics.js
  UI/js/projects/team-backlog.js
  UI/js/projects/team-board.js
  UI/js/projects/team-issues.js
  sass/css/common.scss
Labels: bug

#80 fixing summernote
  UI/js/common.js
Labels: bug

#83 fixes for small bugs
  API/api-components/releases-api.js
  API/api-components/teams-api.js
  Backend/settings.js
  Templates/projects/team-management.pug
  UI/js/projects/project-team.js
Labels: bug

#78 feedback
  API/api-components/common-api.js
  API/api-components/feedback-api.js
  API/api-handler.js
  Backend/common.js
  Backend/db.js
  Backend/dbs/db-feedback.js
  Backend/feedback.js
  Backend/users.js
  Locales/en.json
  Locales/fr.json
  Templates/feedback.pug
  Templates/navbar.pug
  Templates/profile.pug
  UI/js/common.js
  UI/js/feedback.js
  UI/js/navbar.js
  sass/css/common.scss
  velocity.js
Labels: Feature

#85 small fixes
  API/api-components/projects-api.js
  API/api-components/tickets-api.js
  Locales/en.json
  Templates/projects/project-page.pug
  Templates/tickets/tickets-edit.pug
  UI/js/projects/project-page.js
  UI/js/tickets/tickets-edit.js
  sass/css/tickets.scss
Labels: bug, enhancement

#87 minor fixes
  API/api-components/projects-api.js
  Locales/fr.json
  Templates/tickets/tickets-edit.pug
  UI/js/common.js
  UI/js/feedback.js
  UI/js/login.js
  UI/js/modeSelector.js
  UI/js/navbar.js
  UI/js/profile.js
  UI/js/projects/project-page.js
  UI/js/projects/project-team.js
  UI/js/projects/projects-add.js
  UI/js/projects/projects.js
  UI/js/projects/release-page.js
  UI/js/projects/sprint-page.js
  UI/js/projects/tag-page.js
  UI/js/projects/team-backlog.js
  UI/js/projects/team-board.js
  UI/js/projects/team-issues.js
  UI/js/settings.js
  UI/js/tickets/tickets-edit.js
  UI/js/tickets/tickets-entry.js
Labels: bug
